name: Executa jobs e steps com condicionais


on: [push, pull_request]

jobs:
  job-executa-somente-se-push:
    runs-on: ubuntu-latest
    if: github.event_name ==  'push'
    steps:
      - name: Imprime contexto do github
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Imprime contexto do job somente se primeiro passo falhou
        if: failure()
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"    

