name: Escreve coisas Ubuntu e Windows

on: [push]

jobs:
  job-escreve-coisas-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: escrevendo hello world
        run: echo "Hello Wolrd"
      - name: escrevendo versão do git
        run:  git --version 
      - name: escrevendo estrutura de pasta
        run: |
          ls
          pwd
      - name: escreve versao docker
        run: docker -v
  job-escreve-coisas-windows:
    runs-on: windows-latest
    needs: ["job-escreve-coisas-ubuntu"]
    steps:
      - name: Escreve diretorio
        run: Get-Location
      - name: Executa pwd com bash do linux
        run: pwd
        shell: bash

