name: Ações do github

on: [push]

jobs:
   job-hello-word-com-javascript-action:
     runs-on: ubuntu-latest
     steps:
       - name: escreve hello word
         id: greet
         uses: actions/hello-world-javascript-action@master
         with:
             who-to-greet: felipe-rodrigues
       - name: escreve resultado
         run: echo "{{ steps.greet.outputs.time }}"