name: Fazedo coisas com Ações do github

on: [push]

jobs:
   job-hello-word-com-javascript-action:
     runs-on: ubuntu-latest
     steps:
       - name: escreve hello word
         id: greet
         uses: actions/hello-world-javascript-action@master
         with:
             who-to-greet: felipe-rodrigues
       - name: escreve resultado
         run: echo "${{ steps.greet.outputs.time }}"
   job-escreve-infos-do-repositorio:
     runs-on: ubuntu-latest
     steps:
       - name: Clona repositorio pra maquina virtual
         uses: actions/checkout@v2
       - name: Escreve ultimo commit
         run: git log --format="%h" -n 1
       - name: Lista arquivos
         run: ls -a  